### ISSUE TITLE
Improvement: Misc frontend media player improvements (Edited by maintainer)

### ISSUE THREAD

**Issue by Soyvor** [omeryusufyagci/fast-music-remover#15]
**Describe the bug**
Error Handling:

The current error handling is minimal, only showing "An error occurred!". It could be enhanced to give more specific feedback to the user (e.g., network issues, incorrect URL format).
Form Input Validation:

The url field does not validate if the input is a valid YouTube URL. You should add basic validation to ensure the URL is well-formed before sending it to the server.
Video Display:

The video tag is always displayed, even if no video has been processed. You could hide the video player until a valid video URL is returned.
Submit Button Disabled State:

The submit button can still be clicked multiple times during the processing phase. Disable it during the process to avoid duplicate submissions.
Potential Security Risk:

Directly using fetch without sanitizing the URL might lead to vulnerabilities. Make sure the backend sanitizes the URL and ensures the security of the system.

**Comment by omeryusufyagci** [comment]
Hi @Soyvor,

Thank you for your suggestions. As mentioned in my comment on Issue #16, I believe these improvements would be better consolidated into a single, well-defined `Improvement Request`. For detailed feedback and next steps, please refer to my comment there.

I will close this issue to keep everything organized. Feel free to reach out if you have questions.
