### ISSUE TITLE
Testing: Perform Initial Tests on Windows

### ISSUE THREAD

**Issue by omeryusufyagci** [omeryusufyagci/fast-music-remover#18]
We are looking to expand support to Windows users by providing an installable Windows release. Before we proceed to automate a Windows release pipeline, we need to confirm that the current project works well on a Windows environment.

This is a particularly good first issue to take, and a good opportunity to understand the inner workflow of the project. It will also pave the way to reach a greater audience. 

**Objectives**:
- Test Functionality on Windows:
  - Set up the project on a Windows machine by following the manual installation instructions.
  - Run through the core functionality (e.g., processing a video, extracting audio) and verify if everything works as expected.

- Identify Platform-Specific Issues:
  - Report any issues specific to Windows (e.g., file path problems, dependency issues, permission errors).
  - If possible, suggest solutions or fixes to make the project compatible.

- Provide Feedback:
  - Document what worked and what didn't in your testing environment (Windows version, any special setup you needed to do).
  - Suggest improvements to the documentation if there are any changes needed for Windows users.

**Comment by IbrahimHamshari** [comment]
Can you assign me this issue ?

**Comment by omeryusufyagci** [comment]
Hi @IbrahimHamshari, thanks for your interest! 

I've assigned the issue to you. Please take note of each problem you encounter and provide updates to our documentation to ensure a seamless manual installation experience for our Windows users. 

Feel free to reach out if you have any questions along the way

**Comment by readysetlearn** [comment]
Hi @omeryusufyagci

I can't get this to build on Windows 10. I tried with Visual Studio and MSYS2. They both gave errors regarding the inclusion of nlohmann/json.hpp in ConfigManager.h. I tried installing the mingw-w64-x86_64-nlohmann-json package in MSYS2 but it didn't help.

**Comment by omeryusufyagci** [comment]
Hi @readysetlearn thanks for reporting this. I'm expecting quite a few small issues like this to come up here. Let's revisit this with @IbrahimHamshari once his initial review is finished and proposes a set of manual installation instructions for Windows.

**Comment by omeryusufyagci** [comment]
Trying to test on a Mac, I've also run into some problems and just updated the documentation to include details about the ffmpeg path and installation instructions for the JSON library. We can add the Windows instructions in the same collapsable section under Prerequisites. Now it seems to be fine on MacOS and Linux. 

Eventually we should provide an installation script, and detect the paths, update the config file ourselves, but for now let's try to document exhaustively.

**Comment by IbrahimHamshari** [comment]
Yeah, I also ran into some issues with that fixed it, but I have some path errors right now and I'm trying to fix them right now.

**Comment by IbrahimHamshari** [comment]
I've ran into some issues that I think it requires deep knowledge about the code itself, how can I contact you to understand the project more ?

**Comment by omeryusufyagci** [comment]
Thanks @IbrahimHamshari for sharing the details. Indeed, we have some work to do to support both both OSs without cluttering the code base. I have the rough game plan in my mind though:

1. Update `config.json` with dedicated paths:
```json
"ffmpeg_path_unix": "/usr/bin/ffmpeg",
"ffmpeg_path_windows": "C:\\ ...", 
```
Same for the DeepFilter path, and we should put the default paths on Windows.

2. Update the `ConfigManager` to support "1":
We need to add getters here, e.g. `getFFmpegPath()`, which will return the correct value depending on the OS definition. 

```cpp
#ifdef _WIN32
    return getConfigValue("ffmpeg_path_windows");
#else
    return getConfigValue("ffmpeg_path_linux");
#endif
```

3. Update the implementation wrt "2":
Now we can cleanly take these values from the `ConfigManager` singleton, e.g. `configManager.getFFmpegPath()`. 

4. Migrate to `std::filesystem::path`
We already use this to manage paths, but this is an oversight from me that they're hardcoded here. 
Example of what I mean:
```cpp
// instead of
m_chunksDir = m_outputDir + "/chunks";
// use
m_chunksDir = (std::filesystem::path(m_outputDir) / "chunks").string();
```
Of course, to refactor all similar operations for other variables as well. 

5. I believe at this point it should work, but to improve the ease of use of the ffmpeg commands, we should also introduce a `CommandBuilder`. This is where I want to go with this:

```cpp
// Instead of:
std::string ffmpegCommand = ffmpegPath + " -y -i \"" + m_inputVideoPath +
                            "\" -ar 48000 -ac 1 -c:a pcm_s16le \"" + m_outputAudioPath + "\"";

// we should do:
cmd.addArgument(ffmpegPath);
cmd.addFlag("-y");
cmd.addFlag("-i", input);
cmd.addFlag("-ar", "48000");
...
cmd.addArgument(output);
```
I didn't write down the `CommandBuilder` interface here, but I hope you get the idea. 

---

There is a lot to unpack here, and your feedback has been great to identify so many issues. As a high level overview, I think this should work, and I'll try to take a look at this soon (tonight hopefully!). 

Fyi, @andcscott about the `CommandBuilder` as it may affect the class you're writing.

**Comment by IbrahimHamshari** [comment]
Thanks @omeryusufyagci for the insight, I was able to fix the paths. But the problem right now is that "deep-filter-0.5.6-x86_64-unknown-linux-musl" is not suitable for window, I'm not sure though when I try to execute a command on it this happens 
![image](https://github.com/user-attachments/assets/f23195de-42d4-49c5-af1f-df8efe642493)
this error happens when trying to process a video 
![image](https://github.com/user-attachments/assets/b26133a4-a25c-4d40-9dc2-e409064b4097)

**Comment by omeryusufyagci** [comment]
@IbrahimHamshari you found another update needed for the config file! That file is a linux executable, so we have to ensure to use a windows binary. Could you please try with [this](https://github.com/Rikorose/DeepFilterNet/releases/download/v0.5.6/deep-filter-0.5.6-x86_64-pc-windows-msvc.exe) Windows executable?

You'll need to move the downloaded file under the `res` directory and update the `config.json` to point to this path. 
This should resolve the primary problem. 

Can you locate `MediaProcessor` binary under `build/`? It may be an artifact of the problem above.

**Comment by omeryusufyagci** [comment]
Could you try to append the .exe extension [here](https://github.com/omeryusufyagci/fast-music-remover/blob/6d21698a360eed61cb1adccd67c6e647c12112b1/app.py#L95)?

I see that you tested with `./MediaProcessor`; your shell could be smart enough to add the .exe extension, but the system might not recognize the file.

**Comment by IbrahimHamshari** [comment]
Yeah I tried that, same issue.

**Comment by omeryusufyagci** [comment]
Could you please share the full logs in text form, from the start of the backend server? Thanks

**Comment by IbrahimHamshari** [comment]
Here is the log file:
[log.txt](https://github.com/user-attachments/files/17259812/log.txt)

**Comment by omeryusufyagci** [comment]
Have you edited the "./" part of that subprocess call? That's unix syntax; it should be something like `MediaProcessor\\build\\MediaProcessor.exe` (tbt). I'd try to `os.listdir` where you're calling the binary, and perhaps run it with abs path. Is your fork up to date? If above doesn't help, could you push your work-in-progress version? It will help to understand better.
