### ISSUE TITLE
Improvement: Configurable Overlap Duration

### ISSUE THREAD

**Issue by nikhiljangra264** [omeryusufyagci/fast-music-remover#24]
**Current Behavior**:
Currently Overlap duration is constant 0.5

**Suggested Improvement**:
We can give user's to change it using config.json file
user's can set the value in % like 50%
which means if chunk duration is 4s the overlap duration will be 2s.

**Benefits**:
- Short Overlap (e.g., 10-20% of chunk size):
Faster but less quality

- Long Overlap (e.g., 50% or more of chunk size):
 slower but high quality

**Potential Challenges**:
No comment

**Additional Context**:
No comment

**Comment by omeryusufyagci** [comment]
Hi @nikhiljangra264, thaks for the suggestion. This is similar to #20, could you add your suggestion as a comment there, and we'll track it under the same issue? Thanks
