### ISSUE TITLE
Feature: Implement `FFmpegCommandBuilder` to `MediaProcessor`

### ISSUE THREAD

**Issue by omeryusufyagci** [omeryusufyagci/fast-music-remover#31]
Implement an `FFmpegCommandBuilder` class to extend the existing `CommandBuilder`, to establish a high-level API, with methods like overwriteOutput(), setInput(), and for other settings. 

This will simplify `FFmpegController` usage by improving readability and reducing direct flag usage in the codebase. It will also make the implementation more user-friendly, removing the need to know FFmpeg command details.

```cpp
FFmpegCommandBuilder cmd;
cmd.overwriteOutput();
cmd.setInput(inputVideoPath);
cmd.setSampleRate(m_audioConfig.sampleRate);
// ...
```
For more context, see the discussion in #4.

A good first issue as it's a direct extension of an existing class and requires minimal understanding of the full project.

**Comment by andcscott** [comment]
Hi @omeryusufyagci, I should have time to take a look at this issue too sometime this week if you'd like to assign to me

I figure I'm familiar enough and it will allow us to coordinate on #4 but I'll obviously leave it up to you ;)

**Comment by omeryusufyagci** [comment]
hey @andcscott, that'd be great, indeed you already have the context. I couldn't get to that PR just yet, looks good but want to take a closer look. Been busy with some new features. Thanks for taking this on as well!

**Comment by andcscott** [comment]
No problem about the PR, there was no rush. Plus it looks like the project is getting some more attention so that's always good. Thanks for trusting me another issue! I'll be working on this in tandem with #28 this week.
