### ISSUE TITLE
Feature: Add Auto-Configuration for Thread Usage in `MediaProcessor`

### ISSUE THREAD

**Issue by omeryusufyagci** [omeryusufyagci/fast-music-remover#5]
Currently, the thread count uses a default value (see `MediaProcessor::AudioProcessor()`). This improvement aims to allow faster processing times for more capable hardware while ensuring stable operation on all target machines by determining an optimal number of threads.

**Objective:**
- Automatically determine the number of threads based on hardware capabilities using `std::thread::hardware_concurrency()`.
- Allow users to override this value in `config.json` for manual control if needed.
- Update the current implementation to use this dynamic value where applicable.

**Comment by nikhiljangra264** [comment]
I would love to work on this, Could you assign it to me?

**Comment by omeryusufyagci** [comment]
Hi @nikhiljangra264, thanks for your interest! I've assigned the issue to you.

**Comment by nikhiljangra264** [comment]
Hello, I have made a PR regarding this. Please take a look and give me suggestions if any.
