### ISSUE TITLE
Feature: Prebuilt Docker image

### ISSUE THREAD

**Issue by nwithan8** [omeryusufyagci/fast-music-remover#74]
**Description**:
Please consider releasing a prebuilt Docker container to Docker Hub and/or GitHub Container Registry

**Use Case**:
Allow users to use the prebuilt image rather than having to build from source each time. Allows things such as Unraid template and TrueNAS charts.

**Proposed Solution**:
GitHub Action to build and release the Docker image whenever a GitHub release is cut.

**Additional Context**:
Add any other relevant information, screenshots, or examples that help clarify your request.

**Comment by omeryusufyagci** [comment]
Hi @nwithan8, 

This is a very good point, thanks a lot for bringing it up! Will try to plan this asap!

**Comment by omeryusufyagci** [comment]
Hi @nwithan8, thanks again for bringing this up. 

We're now providing a prebuilt image via the github container registry as part of our CI, as you suggested. 
I've updated the readme with [instructions](https://www.youtube.com/watch?v=bhwMsJVydAA) to use it.
Please don't hesitate to let me know if you experience any issues with it!

**Comment by nwithan8** [comment]
Thanks! And in return, I made an Unraid template for this, so users can easily install this container on their servers from the Community Apps Store.
