### ISSUE TITLE
Testing: Add Unit Tests for `MediaProcessor` using Google Test

### ISSUE THREAD

**Issue by omeryusufyagci** [omeryusufyagci/fast-music-remover#8]
To eliminate the need for manual testing and verification of the `MediaProcessor` after every change, unit tests should be added to ensure consistent behavior. Given the nature of the project, this requires appropriate input/output media files to thoroughly test the core functionality of the `MediaProcessor`.

**Objectives**:
1. Find/Generate suitable test I/O for the `MediaProcessor`: 
Identify or generate media files that can be used for testing. Ideally, these should be short (a few seconds long) clips covering different use cases (e.g., video with background music, video with pure vocals, noisy background).

2. Implement Tests Using Google Test:
Add tests for critical operations like audio extraction, filtering, and merging back the processed audio with video.

**Comment by nikhiljangra264** [comment]
I would Love to work on this. Can you assign me this?

**Comment by omeryusufyagci** [comment]
Hi @nikhiljangra264, would be great, thanks!
