### ISSUE TITLE
Is it possible to remove laughter?

### ISSUE THREAD

**Issue by VitaliyAT** [omeryusufyagci/fast-music-remover#81]
Problem is that somebody (my friend in particuar) can't watch sitcoms with background laughter. And I try find how remove background Lauther from soundtracks. As I can imagine that you product can do harder work, so maybe it's possible, or you can upgrade it to remove background laughter too. Could you?

**Comment by sukaha** [comment]
> Problem is that somebody (my friend in particuar) can't watch sitcoms with background laughter. And I try find how remove background Lauther from soundtracks. As I can imagine that you product can do harder work, so maybe it's possible, or you can upgrade it to remove background laughter too. Could you?

Yes, it’s possible — you can try the sound effects removal model in [lyrunomdx](https://lyruno.com/download). I tested it myself and it works really well for removing background laughter. The only caveat is that it doesn’t isolate just the laughter: other effects like applause or rain sounds get removed too.
