### ISSUE TITLE
Improvement: Refactor Flask Backend for Maintainability

### ISSUE THREAD

**Issue by omeryusufyagci** [omeryusufyagci/fast-music-remover#9]
The current implementation of the Flask backend has grown large and disorganized while resolving various issues and adding features. To improve maintainability and readability, a comprehensive refactor is necessary. This aims to encapsulate responsibilities into dedicated classes and remove redundant code.

**Objectives**:

- Add a `VideoProcessor` class to encapsulate video download and processing logic.
- Move methods like `download_youtube_video()`, and `process_video_with_cpp()` into the new VideoProcessor class. Rename methods for clarity, e.g. `download_youtube_video()` should be `download_media()`.
- Add a `Utils` class to encapsulate repeated operations, for file paths, sanitization, and cleanup.
- Improve overall readability of the Flask application, by moving larger functionality into dedicated modules/classes.

Note: The primary goal here is to improve maintainability. Feel free to add suggestions or ideas for further modularizing the code if you notice other areas that could benefit from this effort.

**Comment by VarunParab** [comment]
"Would love to work on this, could you assign it to me?"

**Comment by omeryusufyagci** [comment]
Hi @VarunParab, thanks for your interest! 

I've assigned the issue to you. Resolving this will unblock several other issues, so many thanks for taking it on!

If you'd like to discuss any details as you work through it, please don't hesitate to reach out.

**Comment by VarunParab** [comment]
Hi @omeryusufyagci, I've submitted a pull request addressing the issue. Please let me know if any further changes or clarifications are needed. Looking forward to your feedback!
